sudo: required
services:
  - docker

before_install:
  - docker build -t rajeshcse515/react-test -f ./clinet/Dockerfile.dev ./client

script:
  - docker run rajeshcse515/react-test npm test -- --coverage

after_success:
  - docker build -t rajeshcse515/multi-client ./client
  - docker build -t rajeshcse515/multi-nginx ./nginx
  - docker build -t rajeshcse515/multi-server ./server
  - docker build -t rajeshcse515/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rajeshcse515/multi-client
  - docker push rajeshcse515/multi-nginx
  - docker push rajeshcse515/multi-server
  - docker push rajeshcse515/multi-worker

